app:
  version: 0.1.0

log:
  level: trace

ws:
  orders_addr: ":8182"
  prices_addr: ":8183"

grpc:
  addr: ":8181"
  disable_auth: false
  notifications_addr: ":8184"

exchange:
  info_file: "./data/exchange.json"
  commission: 0.1

parser:
  file: "./data/Binance_ETHUSDT_1m_2022.csv"
  listener_delay: 3ms
#  offset: 1597351740000
#  offset: 1574851020000
