app:
  version: 0.1.0

log:
  level: trace

ws:
  addr: ":8082"

grpc:
  addr: ":8081"
  disable_auth: false

exchange:
  data_file: "./data/Binance_ETHUSDT_1h.csv"
  info_file: "./data/exchange.json"
  delay: 10ms

commission: 0.01