app:
  version: 0.1.0

log:
  level: debug

ws:
  addr: ":8082"

grpc:
  addr: ":8081"
  disable_auth: false

exchange:
  data_file: "./data/Binance_ETHUSDT_minute.csv"
  info_file: "./data/exchange.json"
  delay: 1ms
  offset: 1597351740000
  commission: 0.1